@extends('layouts.public')
@section('title', 'แผนที่ระดับน้ำ '.$province->name_th)
@section('description', 'สถานีระดับน้ำ ThaiWater และรายงานน้ำท่วมใกล้บ้านใน'.$province->fullName())
@section('body-class', 'water-dashboard')
@push('head')
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.css">
    <link rel="stylesheet" href="{{ asset('css/public-water.css') }}?v={{ filemtime(public_path('css/public-water.css')) }}">
@endpush
@section('content')
<main class="wm-page" id="waterPage" data-slug="{{ $province->slug }}">
    <header class="wm-header"><a id="waterHome" href="{{ route('public.province', $province) }}" class="wm-back" aria-label="กลับหน้าจังหวัด"><i class="bi bi-arrow-left" aria-hidden="true"></i></a><div><span class="wm-kicker">FLOODTHAI · WATER EXPLORER</span><h1>ระดับน้ำ <span id="waterTitle">{{ $province->name_th }}</span></h1></div><div class="wm-header-actions"><label for="waterProvince"><span>เลือกจังหวัด</span><select id="waterProvince">@foreach($locations as $p)<option value="{{ $p['slug'] }}" @selected($p['slug'] === $province->slug)>{{ $p['name'] }}</option>@endforeach</select></label><button type="button" id="waterRefresh" aria-label="อัปเดตข้อมูลระดับน้ำ"><i class="bi bi-arrow-clockwise" aria-hidden="true"></i></button></div></header>
    <section class="wm-hero"><div><span class="wm-kicker">รู้ทันน้ำในพื้นที่ของคุณ</span><h2>เห็นระดับน้ำชัด<br>เตรียมพร้อมได้ใกล้ตัว</h2><p>สถานีตรวจวัดจาก ThaiWater และรายงานจากคนในพื้นที่<br>แยกแหล่งข้อมูล อ่านง่าย ในแผนที่เดียว</p><span class="wm-hero-tag"><i class="bi bi-shield-check" aria-hidden="true"></i> ข้อมูลประกอบการเฝ้าระวัง ไม่ใช่การรับรองความปลอดภัย</span></div><small class="wm-art-label">ภาพประกอบ ไม่ใช่สถานการณ์จริง</small></section>
    <section class="wm-metrics" aria-label="สรุปข้อมูลจังหวัด"><div><span class="wm-metric-icon"><i class="bi bi-broadcast" aria-hidden="true"></i></span><span><small>สถานีที่มีข้อมูล</small><strong id="waterStationCount">—</strong></span><em>ThaiWater</em></div><div><span class="wm-metric-icon rose"><i class="bi bi-water" aria-hidden="true"></i></span><span><small>สถานีรายงานล้นตลิ่ง</small><strong id="waterOverflowCount">—</strong></span><em>ไม่รวมข้อมูลเก่า</em></div><div><span class="wm-metric-icon blue"><i class="bi bi-people" aria-hidden="true"></i></span><span><small>รายงานน้ำท่วมสาธารณะ</small><strong id="waterReportCount">—</strong></span><em>12 ชม. ล่าสุด</em></div><div><span class="wm-metric-icon amber"><i class="bi bi-clock" aria-hidden="true"></i></span><span><small>เวลาวัดล่าสุดในจังหวัด</small><strong class="wm-time" id="waterLatest">—</strong></span><em>เวลาไทย</em></div></section>
    <nav class="wm-quick-nav" aria-label="ทางลัดข้อมูลน้ำ"><a href="#waterMap"><i class="bi bi-map" aria-hidden="true"></i> ดูแผนที่จังหวัด</a><a href="#nearby"><i class="bi bi-house-check" aria-hidden="true"></i> เช็กน้ำท่วมใกล้บ้าน</a><span>แยกข้อมูลสถานีและรายงานในพื้นที่ให้ชัดเจน</span></nav>
    <div class="wm-workspace">
        <section class="wm-map-card" aria-label="แผนที่ระดับน้ำ"><header><div><span class="wm-kicker">พื้นที่ที่เลือก</span><h2 id="waterMapTitle">{{ $province->fullName() }}</h2></div><button id="waterFit" type="button"><i class="bi bi-bounding-box" aria-hidden="true"></i> ดูทั้งจังหวัด</button></header><div class="wm-map-tools"><label><input type="checkbox" checked id="waterStationsToggle"> สถานี ThaiWater</label><label><input type="checkbox" checked id="waterReportsToggle"> รายงานน้ำท่วม</label><span><i class="bi bi-info-circle" aria-hidden="true"></i> แตะจุดเพื่อดูรายละเอียด</span></div><div class="wm-map-stage"><div id="waterMap" aria-label="แผนที่จังหวัดที่เลือก"></div><div class="wm-map-chip"><span></span><b id="waterMapChip">{{ $province->name_th }}</b> · เส้นขอบสีเขียวเข้ม</div><div id="waterMapMessage" class="wm-map-message" role="status">กำลังโหลดขอบเขตจังหวัด…</div></div><div class="wm-legend"><strong>สถานี:</strong>@foreach(\App\Support\PublicWaterService::LEVELS as $level)<span><i style="--level-color:{{ $level['color'] }}"></i>{{ $level['label'] }}</span>@endforeach<span><i style="--level-color:#899ba8"></i>ข้อมูลเก่า / ไม่มีเกณฑ์</span></div><p class="wm-map-note">วงกลมมีตัวเลข = ระดับน้ำสถานี · จุดเล็ก = รายงานความลึกน้ำท่วมจากพื้นที่ เป็นคนละหน่วยและคนละเกณฑ์</p><div class="wm-source"><span id="waterStatus" role="status">กำลังโหลดสถานี…</span><a href="https://www.thaiwater.net/" target="_blank" rel="noopener">ข้อมูลระดับน้ำ: ThaiWater สสน. ↗</a></div><p class="wm-boundary-note" id="waterBoundaryNote">ขอบเขตอ้างอิง: geoBoundaries / OpenStreetMap (ODbL), 2017</p></section>
        <aside class="wm-sidebar"><div id="nearby">@include('partials.nearby-flood')</div><section class="wm-detail-card"><span class="wm-kicker">รายละเอียดสถานี</span><div id="waterStationDetail" aria-live="polite"><div class="wm-detail-empty"><i class="bi bi-cursor" aria-hidden="true"></i><h2>เลือกสถานีบนแผนที่</h2><p>ดูระดับน้ำ เทียบตลิ่ง แนวโน้ม และเวลาที่ตรวจวัด</p></div></div></section><section class="wm-station-card"><div class="wm-station-heading"><h2>สถานีในจังหวัด</h2><span id="waterListCount">—</span></div><label class="wm-search"><i class="bi bi-search" aria-hidden="true"></i><input type="search" id="waterSearch" placeholder="ค้นหาชื่อสถานี / อำเภอ" aria-label="ค้นหาสถานี"></label><div id="waterStationList" class="wm-station-list">กำลังโหลดสถานี…</div></section></aside>
    </div>
    <footer class="wm-footer"><span>ระดับน้ำที่สถานีไม่บอกว่าบ้านคุณท่วมหรือไม่ · หากมีอันตราย โทร 1784</span><a href="{{ route('public.map', $province) }}" id="waterReportsLink">แผนที่รายงานและศูนย์พักพิง ↗</a></footer>
</main>
<script type="application/json" id="waterLocations">{!! json_encode($locations, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) !!}</script>
@endsection
@push('scripts')
    <script src="https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.js"></script>
    <script src="{{ asset('js/nearby-flood.js') }}?v={{ filemtime(public_path('js/nearby-flood.js')) }}"></script>
    <script src="{{ asset('js/public-water.js') }}?v={{ filemtime(public_path('js/public-water.js')) }}"></script>
@endpush
