<!doctype html>
<html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>ติดตั้ง FloodThai</title><link rel="stylesheet" href="/css/installer.css"></head>
<body><main class="setup-shell"><header><a class="setup-logo" href="/">F<span>FloodThai</span></a><span class="setup-tag">ติดตั้งง่าย · ข้อมูลอยู่บนโฮสต์ของคุณ</span></header>
<div class="setup-intro"><p class="eyebrow">FLOODTHAI · SETUP ASSISTANT</p><h1>พร้อมดูแลชุมชน<br><span>เริ่มจากการติดตั้งที่ปลอดภัย</span></h1><p>ตรวจความพร้อม เชื่อมต่อฐานข้อมูล และสร้างบัญชีผู้ดูแลในไม่กี่ขั้นตอน<br>ติดตั้งบนโฮสต์ที่รองรับ Laravel โดยไม่จำเป็นต้องใช้ Composer บนโฮสต์</p></div>
<ol class="setup-steps"><li>1 · ตรวจโฮสต์</li><li>2 · ยืนยันเจ้าของ</li><li>3 · ตั้งค่าระบบ</li><li>4 · เริ่มใช้งาน</li></ol>
<?php if ($error) { ?><div class="notice danger" role="alert"><?= $e($error) ?></div><?php } ?>
<?php if ($locked) { ?>
<section class="setup-card"><span class="card-label">ป้องกันการติดตั้งซ้ำ</span><h2>ระบบนี้ติดตั้งแล้ว</h2><p>ตัวติดตั้งถูกล็อก ไม่สามารถเขียนทับฐานข้อมูลหรือเปลี่ยนบัญชีผู้ดูแลได้จากหน้านี้</p><a class="button" href="/login">เข้าสู่ระบบ</a><p class="hint">หากต้องการอัปเดต ใช้คู่มืออัปเดตและสำรองข้อมูลก่อน ห้ามลบ APP_KEY เพื่อเปิดตัวติดตั้งใหม่</p></section>
<?php } elseif ($done) { ?>
<section class="setup-card"><span class="card-label">ตั้งค่าเว็บไซต์สำเร็จ</span><h2>ยินดีต้อนรับสู่ FloodThai</h2><p>สร้างฐานข้อมูล 77 จังหวัด บทบาท และบัญชีผู้ดูแลของคุณแล้ว ตัวติดตั้งถูกล็อกเรียบร้อย</p><div class="notice warning"><strong>ยังไม่ถือว่าพร้อมรับเหตุจริง</strong><p>ตั้งงานอัตโนมัติในแผงควบคุมโฮสต์ก่อน ระบบเตือนภัยและงานคิวต้องทำงานต่อเนื่อง</p></div><a class="button" href="/admin/hosting">ตรวจความพร้อมและดูวิธีตั้งงานอัตโนมัติ</a><a class="secondary-link" href="/provinces">เปิดหน้าเว็บประชาชน</a><p class="hint">ใช้เบอร์และรหัสที่คุณตั้งไว้เข้าสู่ระบบ ระบบจะให้ตั้งยืนยันตัวตน 2 ชั้น จากนั้นตั้งจังหวัด สายด่วน และหน่วยงานผู้รับผิดชอบข้อมูล</p></section>
<?php } else { ?>
<div class="setup-layout"><section class="setup-card setup-checks"><span class="card-label">ขั้นตอนที่ 1</span><h2>ความพร้อมของโฮสต์</h2><p>ไม่เดาจากชื่อแพ็กเกจโฮสต์ ตรวจจากสิ่งที่เครื่องนี้รองรับจริง</p><ul class="check-list"><?php foreach ($checks as $check) { ?><li class="<?= $check['ok'] ? 'pass' : ($check['required'] ? 'fail' : 'warning') ?>"><span aria-hidden="true"><?= $check['ok'] ? '✓' : '!' ?></span><div><strong><?= $e($check['label']) ?></strong><?php if (! $check['ok']) { ?><small><?= $e($check['help']) ?><?= ! $check['required'] ? ' (คำแนะนำ ไม่บังคับ)' : '' ?></small><?php } ?></div></li><?php } ?></ul><?php if (! $ready) { ?><a class="button" href="/install.php">ตรวจอีกครั้ง</a><?php } ?></section>
<section class="setup-card">
<?php if (! $ready) { ?>
<span class="card-label">แก้รายการที่ยังไม่ผ่านก่อน</span><h2>ยังไม่พร้อมติดตั้ง</h2><p>ส่งรายการด้านซ้ายให้ผู้ให้บริการโฮสต์ได้เลย ระบบจะยังไม่เขียนไฟล์ตั้งค่าหรือแก้ฐานข้อมูล</p><div class="notice warning">โฮสต์ที่ลง WordPress ได้ อาจยังไม่รองรับ FloodThai ต้องตั้ง Document Root เป็น <b>public</b> และมี Cron/PHP CLI สำหรับงานอัตโนมัติด้วย</div>
<?php } elseif (! $authenticated) { ?>
<span class="card-label">ขั้นตอนที่ 2</span><h2>ยืนยันว่าคุณเป็นเจ้าของโฮสต์</h2><p>เปิด File Manager หรือ FTP แล้วอ่านค่า <b>token</b> จากไฟล์นี้ ซึ่งอยู่ด้านนอกโฟลเดอร์ public:</p><code class="path">storage/app/installer/setup-key.php</code><p class="hint">รหัสนี้สร้างใหม่แยกกันบนแต่ละโฮสต์ ไม่อยู่ใน ZIP แจกจ่าย และไม่แสดงผ่านหน้าเว็บ</p><form method="post" action="/install.php"><input type="hidden" name="csrf" value="<?= $e($csrf) ?>"><input type="hidden" name="action" value="authenticate"><label for="setup_key">รหัสยืนยันการติดตั้ง</label><input id="setup_key" name="setup_key" type="password" autocomplete="off" required maxlength="64"><button class="button" type="submit">ยืนยันเจ้าของและดำเนินต่อ →</button></form>
<?php } elseif ($state) { ?>
<span class="card-label">ขั้นตอนที่ 3 · ดำเนินการติดตั้ง</span><h2><?= $e(['configure' => 'บันทึกไฟล์ตั้งค่าต่อ', 'migrate' => 'สร้างตารางฐานข้อมูล', 'seed' => 'สร้างข้อมูลตั้งต้นและผู้ดูแล', 'finish' => 'ล็อกตัวติดตั้งและเริ่มใช้งาน'][$state['phase']] ?? 'ตรวจขั้นตอนติดตั้ง') ?></h2><p>ดำเนินทีละขั้นเพื่อลดปัญหาโฮสต์จำกัดเวลา หากเกิดข้อผิดพลาด คุณสามารถกลับมาทำขั้นตอนเดิมต่อได้โดยไม่เปลี่ยนคีย์เข้ารหัส</p><div class="notice info">ไม่ล้างฐานข้อมูลเดิม ไม่เพิ่มข้อมูลเคสจำลอง และยังไม่เปิดรับเหตุจนกว่าผู้ดูแลจะตั้งค่าจังหวัด</div><form method="post" action="/install.php"><input type="hidden" name="csrf" value="<?= $e($csrf) ?>"><input type="hidden" name="action" value="advance"><button class="button" type="submit">ดำเนินขั้นตอนนี้ →</button></form><p class="hint">อย่าปิดหน้าเว็บระหว่างดำเนินการ และอย่าส่งแบบฟอร์มซ้ำพร้อมกัน</p>
<?php } else { ?>
<span class="card-label">ขั้นตอนที่ 3</span><h2>ตั้งค่าระบบของคุณ</h2><p>สร้างฐานข้อมูลว่างและผู้ใช้ฐานข้อมูลในแผงควบคุมโฮสต์ก่อน ไม่ใช้ฐานข้อมูลร่วมกับเว็บไซต์เดิม</p><form method="post" action="/install.php"><input type="hidden" name="csrf" value="<?= $e($csrf) ?>"><input type="hidden" name="action" value="configure">
<fieldset><legend>เว็บไซต์และรูปแบบโฮสต์</legend><label for="app_name">ชื่อระบบ</label><input id="app_name" name="app_name" value="<?= $e($values['app_name'] ?? 'ศูนย์ช่วยเหลือน้ำท่วม') ?>" required maxlength="100"><label for="app_url">URL เว็บไซต์</label><input id="app_url" name="app_url" type="url" placeholder="https://flood.example.org" value="<?= $e($values['app_url'] ?? '') ?>" required><label for="mode">รูปแบบโฮสต์</label><select id="mode" name="mode"><option value="shared" <?= ($values['mode'] ?? '') === 'shared' ? 'selected' : '' ?>>โฮสต์ทั่วไป / ไม่แน่ใจ — อัปเดตหน้าจอเป็นระยะ</option><option value="vps" <?= ($values['mode'] ?? '') === 'vps' ? 'selected' : '' ?>>VPS — ตั้งงานคิวและเปิด Reverb เพิ่มภายหลังได้</option></select><p class="hint">ทั้งสองรูปแบบต้องมี Cron และ PHP CLI ตัวติดตั้งไม่เปิด Reverb ก่อนตั้งค่าและทดสอบ</p></fieldset>
<fieldset><legend>ฐานข้อมูล MySQL / MariaDB</legend><div class="field-row"><div><label for="db_host">โฮสต์ฐานข้อมูล</label><input id="db_host" name="db_host" value="<?= $e($values['db_host'] ?? 'localhost') ?>" required></div><div><label for="db_port">พอร์ต</label><input id="db_port" name="db_port" type="number" min="1" max="65535" value="<?= $e($values['db_port'] ?? '3306') ?>" required></div></div><label for="db_name">ชื่อฐานข้อมูล (รวม prefix ของโฮสต์)</label><input id="db_name" name="db_name" value="<?= $e($values['db_name'] ?? '') ?>" required autocomplete="off"><label for="db_user">ผู้ใช้ฐานข้อมูล</label><input id="db_user" name="db_user" value="<?= $e($values['db_user'] ?? '') ?>" required autocomplete="off"><label for="db_password">รหัสผ่านฐานข้อมูล</label><input id="db_password" name="db_password" type="password" autocomplete="new-password"><p class="hint">ใช้ผู้ใช้ที่มีสิทธิ์เฉพาะฐานข้อมูลนี้ ไม่แนะนำบัญชี root</p></fieldset>
<fieldset><legend>บัญชีผู้ดูแลระบบ</legend><label for="admin_name">ชื่อผู้ดูแล</label><input id="admin_name" name="admin_name" value="<?= $e($values['admin_name'] ?? '') ?>" required maxlength="100"><label for="admin_phone">เบอร์โทรที่ใช้เข้าสู่ระบบ</label><input id="admin_phone" name="admin_phone" type="tel" inputmode="numeric" pattern="0[0-9]{8,9}" value="<?= $e($values['admin_phone'] ?? '') ?>" required autocomplete="username"><label for="admin_password">รหัสผ่านใหม่ (12–72 ตัว มีตัวอักษรและตัวเลข)</label><input id="admin_password" name="admin_password" type="password" minlength="12" maxlength="72" required autocomplete="new-password"><label for="admin_confirmation">ยืนยันรหัสผ่าน</label><input id="admin_confirmation" name="admin_confirmation" type="password" minlength="12" maxlength="72" required autocomplete="new-password"></fieldset>
<button class="button" type="submit">ตรวจฐานข้อมูลและบันทึกการตั้งค่า →</button><p class="hint">ไม่มีรหัสผู้ดูแลร่วมกัน การติดตั้งใหม่จะสร้าง APP_KEY เฉพาะเครื่อง ต้องสำรองคีย์นี้คู่กับฐานข้อมูลเสมอ</p></form>
<?php } ?>
</section></div>
<?php } ?>
<footer>แจกจ่ายตัวระบบได้ · ค่าโฮสต์และเงื่อนไขผู้ให้บริการข้อมูลเป็นของผู้ใช้งานแต่ละราย<br>ก่อนเปิดรับเหตุจริง ต้องตั้งงานอัตโนมัติ ทดสอบฟอร์ม และสำรองข้อมูล</footer></main></body></html>
